config/routes.rb
Rails.application.routes.draw do

get "/stats", to: "shortened_urls#stats", as: :stats
get "shortened/:short_url", to: "shortened_urls#shortened", as: :shortened
post "/shortened_urls/create"
get "/:short_url", to: "shortened_urls#show"

root to: 'shortened_urls#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/shorten.rb
module Shorten
  module Url
      extend ActiveSupport::Concern

      included do
        UNIQUE_ID_LENGTH = 5
        URL_REGEXP = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix

        has_many :trackings

        validates :original_url, presence: true, on: :create

        validates :original_url, format: {
          multiline: true,
          with: URL_REGEXP,
          message: 'You provided invalid URL'
        }
        validates_uniqueness_of :sanitize_url

        before_create :generate_short_url, :sanitize, :set_expiry
      end

      def new_url?
        find_duplicate.nil?
      end

      def sanitize
        self.original_url.strip!
        self.sanitize_url = self.original_url.downcase.gsub(/(https?:\/\/)|(www\.)/,"")
        self.sanitize_url = "http://#{self.sanitize_url}"
      end
      
      def set_expiry
        self.expiration = Time.now.next_month
      end

      def remaining_days
        expired? ? 0 : ((self.expiration.to_time - Time.now)/1.day).to_i
      end

      def expired?
        (self.expiration.to_time - Time.now)/1.day <= 0
      end

  end
end

app/models/tracking.rb
class Tracking < ApplicationRecord
  belongs_to :url
end

app/models/url.rb
class Url < ApplicationRecord
  include Shorten::Url


        def total_count
           self.trackings.count
        end

        def top_countries
          self.trackings.select(:country).group(:country).order(count: :desc).limit(3).pluck(:country).reject(&:empty?)
        end

        def generate_short_url
          url = ([*('a'..'z'),*('0'..'9')]).sample(UNIQUE_ID_LENGTH).join
          old_url = Url.where(short_url: url).last

          if old_url.present?
            self.generate_short_url
          else
            self.short_url = url
          end
        end

        #Check duplicate url
        def find_duplicate
          Url.find_by_sanitize_url(self.sanitize_url)
        end

      




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  before_action :find_url, only: [:show, :shortened]
  skip_before_action :verify_authenticity_token

  def index
    @url = Url.new
  end

  def show
    if @url.present?
      if @url.expired?
        @message = "URL Expired"
      else
        record_activity
        redirect_to @url.sanitize_url unless @url.expired?
      end
    else
      @message = "URL doesnot exist"
    end
  end

  def create
    @url = Url.new(url_params)
    @url.sanitize_url
    respond_to do |format|
      if @url.new_url?
        if  @url.save
          host = request.host_with_port
          @short_url = host + '/' + @url.short_url
          format.html { redirect_to @url, notice: 'url was successfully created.' }
          format.js
           format.json { render :show, status: :created, location: @url }
        else
          format.html { render action: "index" }
          format.js
          format.json { render json: @url.errors, status: :unprocessable_entity }
        end
      else
        format.js
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  def stats
    #@urls = Url.includes(:trackings).paginate(page: params[:page], per_page: 30)
    @urls = Url.preload(:trackings).paginate(page: params[:page],per_page: 30)

    @host = request.host_with_port
  end

  def shortened
    @url = Url.find_by_short_url(params[:short_url])
    host = request.host_with_port
    @short_url = host + '/' + @url.short_url
    @original_url = @url.sanitize_url
  end

  def fetch_original_url
    fetch_url = Url.find_by_short_url(params[:short_url])
    redirect_to fetch_url.sanitize_url
  end

  private
  def find_url
    @url = Url.find_by_short_url(params[:short_url])
  end

  def url_params
    params.require(:url).permit(:original_url)
  end

  def record_activity
    result = Geocoder.search(request.remote_ip).first
    @url.trackings.create(
      ip: result.data.fetch('ip',''),
      country: result.data.fetch('country','')
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', async: true %>
  </head>

  <body class="pb-5">
      <div class="container">
        <%= yield %>
      </div>
      <%#= render 'shared/debug' %>
  </body>
</html>

app/views/shared/_debug.html.erb
<% if Rails.env.development? %>
    <div class="container">
        <div class="card">
            <div class="card-header">
                Params
            </div>
            <div class="card-body">
                    <code>
                        <%= debug(params) %>
                    </code>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_validation-messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
        <p class="font-weight-bold"><%= pluralize(object.errors.count, "error") %> prohibited this <%= "#{object.class.name.downcase}" %> from being saved:</p>
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shortened_urls/_form-fields.html.erb
<div class="form-group">
    <%= f.label :original_url %>
    <%= f.text_field :original_url, class: "form-control" %>
    <%= f.submit class: "btn btn-success", value: "SHORTEN" %>
</div>

app/views/shortened_urls/_form.html.erb
<%= form_for @url,  :as => :url, url: shortened_urls_create_path(@url), html:{id:"short_url",remote:true} do |f| %>
    <%= render 'form-fields', f: f %>
<% end  %>

app/views/shortened_urls/_shorten-url.html.erb
<% if object.present? %>
    <div >
        <p>Here is your shorten URL:- </p>
        <%="#{@short_url}" %>
    </div>
<% end %>

app/views/shortened_urls/create.js.erb
$('#short_url #errors').append('')
<% if @url.errors.any? %>
  $('#errors').append("<%= escape_javascript render(:partial => 'shared/validation-messages', :locals => { :object => @url }) %>");
<% else %>
  $('#short_url_link').append("<%= escape_javascript render(:partial => 'shorten-url', :locals => { :object => @url }) %>");
<% end %>


setInterval(function(){ $("#errors").html('') }, 5000);

app/views/shortened_urls/index.html.erb
<h2>Welcome to shorten url application</h2>

<div id="errors"></div>
<%= render 'form' %>

<div id="short_url_link"></div>

app/views/shortened_urls/shortened.html.erb
<center>
<h2>Original url is:</h2>
<%= @original_url %> <br>
<h2>Shorten url is:</h2> <%= @short_url %>
</center>

app/views/shortened_urls/show.html.erb
<% if @message.present? %>
  <h1>404: <%= "#{@message}" %>. </h1>
<% else %>
  <h1>Your short link is expired.</h1>
<% end %>

app/views/shortened_urls/stats.html.erb
<h2>Analytics</h2>

  <% @urls.each do |url| %>
  <%#= url.inspect %>
  <div class="block">
      <h5><%= url.original_url %></h5>
      <p><%= @host +'/' + url.short_url %></p>
      <div>
        <p>Total clicks: <%= url.total_count %> </p>
        <p>Top Countries: <%= url.top_countries.map {|code| c = ISO3166::Country.new(code); c.data['name']}.join(',') %> </p>
      </div>
    </div>
  <% end %>

<%= will_paginate @urls %>